const gacha = {
  id: 'dokidoki-dousei',
  slug: 'dokidoki-dousei',
  title: 'ドキドキ同棲生活、はじめました！',
  type: 'アイミーボックス',
  banner: '/images/gacha/dokidoki-dousei/banner.jpg',
  status: '開催中',
  infoStatus: '確認済み',
  startDate: '2026/06/12 15:00',
  endDate: '2026/08/07 14:59',
  description: 'ドキドキ同棲生活、はじめました！の限定ガチャです。',
  items: [
    { id: 'dokidoki-dousei-hokahoka-yuagari-pajama', rarity: 'SSR', category: '衣装', name: 'ほかほか湯上がりパジャマ', image: '/images/items/dokidoki-dousei/01.png' },
    { id: 'dokidoki-dousei-daradara-sakuranbo-pajama', rarity: 'SSR', category: '衣装', name: 'だらだらさくらんぼパジャマ', image: '/images/items/dokidoki-dousei/02.png' },
    { id: 'dokidoki-dousei-honwari-tareme-mizuiro', rarity: 'SSR', category: '目', name: 'ほんわりタレ目(水色)', image: '/images/items/dokidoki-dousei/03.png' },
    { id: 'dokidoki-dousei-amenohi-nure-long-purple', rarity: 'SSR', category: '髪型', name: '雨の日濡れロング(紫)', image: '/images/items/dokidoki-dousei/04.png' },
    { id: 'dokidoki-dousei-kusekke-long-gold', rarity: 'SSR', category: '髪型', name: '癖っ毛ロング(金)', image: '/images/items/dokidoki-dousei/05.png' },
    { id: 'dokidoki-dousei-kusekke-long-pink', rarity: 'SSR', category: '髪型', name: '癖っ毛ロング(ピンク)', image: '/images/items/dokidoki-dousei/06.png' },
    { id: 'dokidoki-dousei-amenohi-nure-long-beige', rarity: 'SSR', category: '髪型', name: '雨の日濡れロング(ベージュ)', image: '/images/items/dokidoki-dousei/07.png' },
    { id: 'dokidoki-dousei-neoki-mofumofu-long-cha', rarity: 'SSR', category: '髪型', name: '寝起きもふもふロング(茶)', image: '/images/items/dokidoki-dousei/08.png' },
    { id: 'dokidoki-dousei-neoki-mofumofu-long-gray', rarity: 'SSR', category: '髪型', name: '寝起きもふもふロング(灰)', image: '/images/items/dokidoki-dousei/09.png' },
    { id: 'dokidoki-dousei-ohana-pop-hairpin', rarity: 'SR', category: '髪飾り', name: 'おはなポップヘアピン', image: '/images/items/dokidoki-dousei/10.png' },
    { id: 'dokidoki-dousei-ribbon-eye-mask', rarity: 'SR', category: '髪飾り', name: 'リボンアイマスク', image: '/images/items/dokidoki-dousei/11.png' },
    { id: 'dokidoki-dousei-fuwafuwa-hair-band', rarity: 'SR', category: '髪飾り', name: 'ふわふわヘアバンド', image: '/images/items/dokidoki-dousei/12.png' },
    { id: 'dokidoki-dousei-kimi-no-shirt', rarity: 'SR', category: '衣装', name: 'キミのシャツ', image: '/images/items/dokidoki-dousei/13.png' },
    { id: 'dokidoki-dousei-iyashi-tareme-purple', rarity: 'SR', category: '目', name: '癒しタレ目(紫)', image: '/images/items/dokidoki-dousei/14.png' },
    { id: 'dokidoki-dousei-yuagari-hoppe', rarity: 'SR', category: 'メイク', name: '湯上がりほっぺ', image: '/images/items/dokidoki-dousei/15.png' },
    { id: 'dokidoki-dousei-terease-hoppe', rarity: 'SR', category: 'メイク', name: 'てれあせほっぺ', image: '/images/items/dokidoki-dousei/16.png' },
    { id: 'dokidoki-dousei-mou-okiruno', rarity: 'SR', category: 'チェキフレーム', name: 'もう起きるの?', image: '/images/items/dokidoki-dousei/17.png' },
    { id: 'dokidoki-dousei-nidone-no-yokan', rarity: 'SR', category: 'チェキフレーム', name: '二度寝の予感', image: '/images/items/dokidoki-dousei/18.png' },
    { id: 'dokidoki-dousei-yume-genjitsu', rarity: 'SR', category: 'チェキフレーム', name: '夢?現実?', image: '/images/items/dokidoki-dousei/19.png' },
    { id: 'dokidoki-dousei-usuakari-black-living', rarity: 'SR', category: '背景', name: '薄明かりの黒基調リビング', image: '/images/items/dokidoki-dousei/20.png' },
    { id: 'dokidoki-dousei-asa-nukumori-oneroom', rarity: 'SR', category: '背景', name: '朝のぬくもりワンルーム', image: '/images/items/dokidoki-dousei/21.png' },
  ],
}

export default gacha